### ISSUE TITLE
Allow additional metadata

### ISSUE THREAD

**Issue by bocytko** [zalando-stups/swagger-ui#12]
Similar to #7 it would be great to include even more custom metadata:
- Response times (already nicely rendered today as table - see Cart API)

```
        | 95thPercentile | 98thPercentile | 99thPercentile | 999thPercentile |
        |----------------|----------------|----------------|-----------------|
        | 00 ms          | 00 ms          | 00 ms          | 00 ms           |
```
- API purpose tags (#retailer, #merchant, #platform, ...) - even badges would be possible:

https://img.shields.io/badge/API-merchant-blue.svg
https://img.shields.io/badge/API-retailer-yellow.svg
https://img.shields.io/badge/API-platform-orange.svg

![Retailer](https://img.shields.io/badge/API-retailer-yellow.svg)
![Platform](https://img.shields.io/badge/API-platform-orange.svg)
![Merchant](https://img.shields.io/badge/API-merchant-blue.svg)

**Comment by fmueller** [comment]
Will be topic of tooling around API portal, not API reference documentation at the moment.
