### ISSUE TITLE
Show application URL

### ISSUE THREAD

**Issue by bocytko** [zalando-stups/swagger-ui#6]
In parallel to the service name it would be great to know the URL of the service exposing the API.

Twintip had already crawled the service, so this information should be easily accessible. Plus, not all APIs correctly fill the `host` parameter in the spec, so that `Try Out` does not reveal the right service URL. Example: "Users API".

**Comment by fmueller** [comment]
Somehow relates to #10

**Comment by fmueller** [comment]
Backend is ready:
https://github.com/zalando-stups/twintip-storage/pull/15
https://github.com/zalando-stups/twintip-crawler/pull/24

**Comment by bocytko** [comment]
:+1:

**Comment by fmueller** [comment]
This repository is migrated to a mono repository, issue is now at https://github.com/zalando-incubator/api-discovery/issues/4
