### ISSUE TITLE
Include the API name into the page URLs in order to make them valid permanent URLs

### ISSUE THREAD

**Issue by jukey** [zalando-stups/swagger-ui#8]
## Issue.

Would it be possible to add the name of the API into the URL in order to allow som kind of permanent links? Currently I just can point people to the start page and tell them to use the pull down menu in the upper right part of the page.
## Example:

In order to point to the method 'GET templates' for the 'Quilt API' I currently have to
1. go to this page: https://swagger.architecture.zalan.do
2. select Quilt from the list of APIs in the drop down menu and
3. click on the 'GET templates' method link

The URL switches to:
- https://swagger.architecture.zalan.do/#!/templates/get_templates

However this URL does not work for someone using it directly.

A working URL should look like:
- https://swagger.architecture.zalan.do/#!/quil/templates/get_templates

**Comment by fmueller** [comment]
This repository is migrated to a mono repository, issue is now at zalando-incubator/api-discovery#6
