### ISSUE TITLE
Authentication does not work for APIs deployed on https://swagger.architecture.zalan.do

### ISSUE THREAD

**Issue by jukey** [zalando-stups/swagger-ui#9]
In the central API directory at https://swagger.architecture.zalan.do it's currently not possible to try out the APIs provided.

![swagger ui 2016-06-24 16-19-45](https://cloud.githubusercontent.com/assets/295928/16340280/8e65fbee-3a27-11e6-991f-18d36eb496f5.png)

Selecting a request I get all the parameters I could use within the request and on top of this page in th right corner there is a 'switch' symbol that is turned off. Next to the switch there is a red '!'-Symbol that allows to gather the scope for the method while doing a mouse over.

However turning 'on' the switch enables a dialog that let you choose the scope (permission). After doing that it leads always to an error message like this:

```
{
error: "invalid_request",
error_description: "Access Token not valid"
}
```

Beside the fact, that authentication is hard to discover (the 'switch' or '!'-symbol are not self explaining) it should work or at least tell me why it is not working.

**Comment by fmueller** [comment]
Authentication will be disabled by default in near future, as developers should exercise APIs with tools like postman or curl directly.
